### ISSUE TITLE
sqs-to-dc: latest code is failing to filter --record-path

### ISSUE THREAD

**Issue by pindge** [opendatacube/odc-tools#242]
## the command that was ran 

```
"sqs-to-dc --skip-lineage --allow-unsafe dea-dev-eks-ows 's2a_nrt_granule s2b_nrt_granule wofs_albers ls5_fc_albers ls7_fc_albers ls8_fc_albers' --record-path 'WOfS/WOFLs/v2.1.5/combined/*/*/*/*/*/*.yaml' --record-path 'fractional-cover/fc/v2.2.1/*/*/*/*/*/*/*.yaml' --record-path 'L2/sentinel-2-nrt/S2MSIARD/*/*/ARD-METADATA.yaml'"
```

## The logging from the command
```
[2021-07-06 03:27:21,857] {pod_launcher.py:173} INFO - Event: datacube-index-0c4bb7c457ff4b8e8a95e284319b5cd4 had an event of type Running
[2021-07-06 03:27:23,458] {pod_launcher.py:156} INFO - b'WARNING:root:Key: baseline/s2a_ard_granule/2015-08-01/S2A_OPER_MSI_ARD_TL_EPA__20160821T103623_A000557_T52LHH_N02.04/eo3-ARD-METADATA.odc-metadata.yaml not in specified list of record_paths, deleting message from the queue.\n'
[2021-07-06 03:27:23,654] {pod_launcher.py:156} INFO - b'/env/lib/python3.8/site-packages/odc/apps/dc_tools/sqs_to_dc.py:138: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.\n'
[2021-07-06 03:27:23,654] {pod_launcher.py:156} INFO - b'  data = load(obj["Body"].read())\n'
[2021-07-06 03:27:23,657] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2021-07-06 03:27:23,657] {pod_launcher.py:156} INFO - b'  File "/env/bin/sqs-to-dc", line 8, in <module>\n'
[2021-07-06 03:27:23,657] {pod_launcher.py:156} INFO - b'    sys.exit(cli())\n'
[2021-07-06 03:27:23,657] {pod_launcher.py:156} INFO - b'  File "/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__\n'
[2021-07-06 03:27:23,657] {pod_launcher.py:156} INFO - b'    return self.main(*args, **kwargs)\n'
[2021-07-06 03:27:23,657] {pod_launcher.py:156} INFO - b'  File "/env/lib/python3.8/site-packages/click/core.py", line 782, in main\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'    rv = self.invoke(ctx)\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'  File "/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'    return ctx.invoke(self.callback, **ctx.params)\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'  File "/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'    return callback(*args, **kwargs)\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'  File "/env/lib/python3.8/site-packages/odc/apps/dc_tools/sqs_to_dc.py", line 376, in cli\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'    success, failed = queue_to_odc(\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'  File "/env/lib/python3.8/site-packages/odc/apps/dc_tools/sqs_to_dc.py", line 241, in queue_to_odc\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'    index_update_dataset(\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'  File "/env/lib/python3.8/site-packages/odc/apps/dc_tools/utils.py", line 69, in index_update_dataset\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'    raise IndexingException(\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b'odc.apps.dc_tools.utils.IndexingException: Failed to create dataset with error No matching Product found for dataset 4a4422b2-4697-4443-a75f-f0ab3e4c1e58\n'
[2021-07-06 03:27:23,658] {pod_launcher.py:156} INFO - b' The URI was s3://dea-public-data/baseline/s2a_ard_granule/2015-08-01/S2A_OPER_MSI_ARD_TL_EPA__20160821T103623_A000557_T52LHH_N02.04/eo3-ARD-METADATA.odc-metadata.yaml\n'
[2021-07-06 03:27:24,683] {pod_launcher.py:173} INFO - Event: datacube-index-0c4bb7c457ff4b8e8a95e284319b5cd4 had an event of type Failed
[2021-07-06 03:27:24,683] {pod_launcher.py:284} INFO - Event with job id datacube-index-0c4bb7c457ff4b8e8a95e284319b5cd4 Failed
[2021-07-06 03:27:24,694] {pod_launcher.py:173} INFO - Event: datacube-index-0c4bb7c457ff4b8e8a95e284319b5cd4 had an event of type Failed
[2021-07-06 03:27:24,694] {pod_launcher.py:284} INFO - Event with job id datacube-index-0c4bb7c457ff4b8e8a95e284319b5cd4 Failed
```

## Summary
```
The URI was s3://dea-public-data/baseline/s2a_ard_granule/2015-08-01/S2A_OPER_MSI_ARD_TL_EPA__20160821T103623_A000557_T52LHH_N02.04/eo3-ARD-METADATA.odc-metadata.yaml\n'
```
is not in the `--record-path` and should be safely ignored.

## old code behaviours

```
[2021-07-06 03:15:46,802] {pod_launcher.py:156} INFO - b'WARNING:root:Dataset already exists, not indexing\n'
[2021-07-06 03:15:46,839] {pod_launcher.py:156} INFO - b'WARNING:root:Key: baseline/ga_ls8c_ard_3/107/067/2021/06/19/ga_ls8c_ard_3-2-0_107067_2021-06-19_final.odc-metadata.yaml not in specified list of record_paths, deleting message from the queue.\n'
[2021-07-06 03:15:47,018] {pod_launcher.py:156} INFO - b'ERROR:root:Failed to create dataset with error No matching Product found for dataset 33d068f8-535b-4a99-9414-5953232452a7\n'
[2021-07-06 03:15:47,018] {pod_launcher.py:156} INFO - b' The URI was s3://dea-public-data/baseline/ga_ls8c_ard_3/107/067/2021/06/19/ga_ls8c_ard_3-2-0_107067_2021-06-19_final.odc-metadata.yaml\n'
[2021-07-06 03:15:47,047] {pod_launcher.py:156} INFO - b'WARNING:root:Key: baseline/ga_ls7e_ard_3/096/081/2021/01/20/ga_ls7e_ard_3-2-0_096081_2021-01-20_final.odc-metadata.yaml not in specified list of record_paths, deleting message from the queue.\n'
[2021-07-06 03:15:47,252] {pod_launcher.py:156} INFO - b'ERROR:root:Failed to create dataset with error No matching Product found for dataset d15f7cf1-b461-4dc0-bc8e-87b5581e4e75\n'
[2021-07-06 03:15:47,253] {pod_launcher.py:156} INFO - b' The URI was s3://dea-public-data/baseline/ga_ls7e_ard_3/096/081/2021/01/20/ga_ls7e_ard_3-2-0_096081_2021-01-20_final.odc-metadata.yaml\n'
```

**Comment by kieranricardo** [comment]
Fixed with #243
