### ISSUE TITLE
s3-to-dc fails to list

### ISSUE THREAD

**Issue by nikkopante** [opendatacube/odc-tools#382]
I am following the [tutorial](https://datacube-core.readthedocs.io/en/latest/ops/indexing.html#s3-indexing-example) to deploy a Data Core in a Windows local machine. I am instead using Anaconda instead of Miniconda since I have other projects too. I have done the steps in the tutorial but when performing :

`s3-to-dc --no-sign-request 's3://dea-public-data/geomedian-australia/v2.1.0/L8/**/*.yaml' ls8_nbart_geomedian_annual`

I get this error:

```
  File "C:\Users\Nikko\anaconda3\envs\cubeenv\lib\site-packages\odc\aio\__init__.py", line 433, in find
    raise IOError(f"Failed to list: {url}")
OSError: Failed to list: s3://deafrica-sentinel-2/sentinel-s2-l2a-cogs/37/M/CS/2017/10/
```

I have tried changing the tool from `odc_apps_dc_tools` to `odc-apps-dc-tools`. But will arrive to a different error:
```
Successfully installed aiobotocore-1.4.1 aiohttp-3.7.4.post0 aioitertools-0.8.0 async-timeout-3.0.1 boto3-1.17.106 botocore-1.20.106 chardet-4.0.0 idna-2.10 multidict-5.1.0 odc-apps-dc-tools-0.2.0a1 odc-cloud-0.2.0a0 odc-io-0.2.0a0 odc-stac-0.2.0a5 pystac-1.1.0 pystac-client-0.2.0 requests-2.25.1 s3transfer-0.4.2 wrapt-1.12.1 yarl-1.6.3

(cubeenv) D:\Documents\GRASPED\OpenDataCube>datacube product add https://data.dea.ga.gov.au/geomedian-australia/v2.1.0/product-definition.yaml
Adding "ls8_nbart_geomedian_annual" (this might take a while) DONE
Adding "ls7_nbart_geomedian_annual" (this might take a while) DONE
Adding "ls5_nbart_geomedian_annual" (this might take a while) DONE

(cubeenv) D:\Documents\GRASPED\OpenDataCube>s3-to-dc --no-sign-request 's3://dea-public-data/geomedian-australia/v2.1.0/L8/**/*.yaml' ls8_nbart_geomedian_annual
Traceback (most recent call last):
  File "C:\Users\Nikko\anaconda3\envs\cubeenv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Nikko\anaconda3\envs\cubeenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nikko\anaconda3\envs\cubeenv\Scripts\s3-to-dc.exe\__main__.py", line 4, in <module>
  File "C:\Users\Nikko\anaconda3\envs\cubeenv\lib\site-packages\odc\apps\dc_tools\s3_to_dc.py", line 20, in <module>
    from odc.index.stac import stac_transform, stac_transform_absolute
ModuleNotFoundError: No module named 'odc.index.stac'
```

Here are my installed packages when `pip freeze`
```
affine==2.3.0
aiobotocore==1.4.1
aiohttp==3.7.4.post0
aioitertools==0.8.0
argon2-cffi @ file:///D:/bld/argon2-cffi_1605217273648/work
async-generator==1.10
async-timeout==3.0.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1629908509068/work
bokeh @ file:///D:/bld/bokeh_1625757104898/work
boto3==1.17.106
botocore==1.20.106
brotlipy==0.7.0
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1619593780156/work
certifi==2021.5.30
cffi @ file:///D:/bld/cffi_1625835497933/work
cftime @ file:///D:/bld/cftime_1621553914127/work
chardet==4.0.0
click==7.1.2
click-plugins==1.1.1
cligj @ file:///home/conda/feedstock_root/build_artifacts/cligj_1622246659049/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1631273254894/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
cryptography @ file:///D:/bld/cryptography_1616851649655/work
cycler==0.10.0
cytoolz==0.11.0
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1630711077912/work
datacube @ file:///home/conda/feedstock_root/build_artifacts/datacube_1629250885499/work
debugpy @ file:///D:/bld/debugpy_1627075474676/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1631346842025/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
distributed @ file:///D:/bld/distributed_1630719174113/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1605121927639/work/dist/entrypoints-0.3-py2.py3-none-any.whl
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1630424910447/work
greenlet @ file:///D:/bld/greenlet_1628272304925/work
HeapDict==1.0.1
idna==2.10
importlib-metadata @ file:///D:/bld/importlib-metadata_1630267647146/work
ipykernel @ file:///D:/bld/ipykernel_1631291286000/work/dist/ipykernel-6.4.1-py3-none-any.whl
ipython @ file:///D:/bld/ipython_1630172686858/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1631590360471/work
jedi @ file:///D:/bld/jedi_1610146948662/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1621419064915/work
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1589369830981/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1614815863336/work
jupyter @ file:///D:/bld/jupyter_1611872058257/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1630336909568/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1616560109969/work
jupyter-core @ file:///D:/bld/jupyter_core_1612125450516/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1631590465624/work
kiwisolver @ file:///D:/bld/kiwisolver_1630173896207/work
lark-parser @ file:///home/conda/feedstock_root/build_artifacts/lark-parser_1630320752939/work
locket==0.2.0
MarkupSafe @ file:///D:/bld/markupsafe_1621455847127/work
matplotlib @ file:///D:/bld/matplotlib-suite_1628881903140/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
mistune @ file:///D:/bld/mistune_1624941477207/work
msgpack @ file:///D:/bld/msgpack-python_1610121836457/work
multidict==5.1.0
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1629120697898/work
nbconvert @ file:///D:/bld/nbconvert_1624472961560/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1617163391303/work
netCDF4 @ file:///D:/bld/netcdf4_1630453197601/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1628690102344/work
numpy @ file:///D:/bld/numpy_1629092230867/work
odc-apps-dc-tools==0.2.1.dev2683
odc-cloud==0.2.0a0
odc-io==0.2.0a0
odc-stac==0.2.1.dev2683
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1625323647219/work
pandas @ file:///D:/bld/pandas_1631466259165/work
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1617148930513/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1617910651905/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///D:/bld/pillow_1630696805646/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1622586138406/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1629903925368/work
psutil @ file:///D:/bld/psutil_1610127325750/work
psycopg2 @ file:///D:/bld/psycopg2-split_1623910109981/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1629119114968/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyparsing==2.4.7
pyproj @ file:///D:/bld/pyproj_1630728978659/work
PyQt5==5.12.3
PyQt5_sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
pyrsistent @ file:///D:/bld/pyrsistent_1610147004705/work
PySocks @ file:///D:/bld/pysocks_1610291742246/work
pystac==1.1.0
pystac-client==0.2.0
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1612179539967/work
pywin32==301
pywinpty @ file:///D:/bld/pywinpty_1630550473294/work/target/wheels/pywinpty-1.1.4-cp38-none-win_amd64.whl
PyYAML==5.4.1
pyzmq @ file:///D:/bld/pyzmq_1628233052116/work
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole_1625023841584/work
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1630767961547/work
rasterio==1.2.8
requests==2.25.1
s3transfer==0.4.2
scipy @ file:///C:/bld/scipy_1628206591178/work
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
Shapely==1.7.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
snuggs==1.4.7
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
SQLAlchemy @ file:///D:/bld/sqlalchemy_1629315096852/work
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1616261298899/work
terminado @ file:///D:/bld/terminado_1631128482238/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1621261527237/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1600973991856/work
tornado @ file:///D:/bld/tornado_1610094858390/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1630423529112/work
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1622748266870/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1624634538755/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
widgetsnbextension @ file:///D:/bld/widgetsnbextension_1605475695976/work
win-inet-pton @ file:///D:/bld/win_inet_pton_1610147566231/work
wrapt==1.12.1
xarray @ file:///home/conda/feedstock_root/build_artifacts/xarray_1627311788418/work
yarl==1.6.3
zict==2.0.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1625284368454/work
```

How can I resolve this?

**Comment by Kirill888** [comment]
@cnpante12 on windows `'` is not stripped away by the shell like in Linux, so please replace `'` with `"`.
Also your environment is broken, we had quite a bit of restructure in `odc-` libraries, please uninstall all `odc-*` libs, then install again and only from PyPI (don't use `--extra-index-url` option please)

**Comment by Kirill888** [comment]
@alexgleith it could also be that apps have changes that are not on pypi yet

**Comment by Kirill888** [comment]
I confirmed that it's to do with pypi version being too old, 
@cnpante12 can you please try

```
pip install https://packages.dea.ga.gov.au/odc-apps-dc-tools/odc_apps_dc_tools-0.2.1.dev2726-py3-none-any.whl
```

then
```
s3-to-dc --no-sign-request "s3://dea-public-data/geomedian-australia/v2.1.0/L8/**/*.yaml" ls8_nbart_geomedian_annual
```

note change in quotes from command in docs.

@alexgleith do you want to test new publishing strategy by bumping version in `odc-apps-dc-tools` and then updating the branch (see PR)

**Comment by nikkopante** [comment]
Thank you @Kirill888 and @alexgleith !

**Comment by ZoloKiala** [comment]
Can you please provide an example of using s3-to-dc with Digital Earth Africa ? I can't see examples for DEAutralia.

**Comment by alexgleith** [comment]
Can you please raise a new issue, @ZoloKiala

**Comment by ZoloKiala** [comment]
@alexgleith Apologies. I was able to address the issue.
