### ISSUE TITLE
Trying to index sentinel data into open data cude using this command stac-to-dc --catalog-href='https://earth-search.aws.element84.com/v0/' --bbox='25,20,35,30' --collections='sentinel-s2-l2a-cogs' --datetime='2020-01-01/2020-03-31' .But it shows exception

### ISSUE THREAD

**Issue by chiranjivSharma** [opendatacube/odc-tools#586]
/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/pystac_client/client.py:186: NoConformsTo: Server does not advertise any conformance classes.
  warnings.warn(NoConformsTo())
Traceback (most recent call last):
  File "/home/bel/miniconda3/envs/cubeenv1/bin/stac-to-dc", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/odc/apps/dc_tools/stac_api_to_dc.py", line 302, in cli
    added, failed, skipped = stac_api_to_odc(
                             ^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/odc/apps/dc_tools/stac_api_to_dc.py", line 159, in stac_api_to_odc
    search = client.search(**config)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/pystac_client/client.py", line 591, in search
    raise DoesNotConformTo(
pystac_client.warnings.DoesNotConformTo: Server does not conform to ITEM_SEARCH, There is not fallback option available for search.

**Comment by alexgleith** [comment]
Can you please share what parameters you've used for the tool?

I think you may be using a STAC API endpoint/catalog URL that isn't appropriate.

**Comment by alexgleith** [comment]
Oh, I see it's in your title `https://earth-search.aws.element84.com/v0/`

Please use their V1 API: `earth-search.aws.element84.com/v1/`

**Comment by chiranjivSharma** [comment]
stac-to-dc --catalog-href='https://earth-search.aws.element84.com/v1/' --bbox='25,20,35,30' --collections='sentinel-s2-l2a-cogs' --datetime='2023-01-01/2023-03-31' .....used this v1 api ,getting below mentioned message

11/03/2023 03:58:53: WARNING: Didn't find any items, finishing.
Added 0 Datasets, failed 0 Datasets, skipped 0 Datasets


could you help on this.

**Comment by alexgleith** [comment]
Oh, you need to change the name of the collection to the new one.

**Comment by chiranjivSharma** [comment]
could you help on identifying the new collection name

**Comment by alexgleith** [comment]
Sorry, yeah. It's this one: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a

The name is `sentinel-2-l2a`.

I'll update the documentation.

**Comment by chiranjivSharma** [comment]
stac-to-dc --catalog-href='https://earth-search.aws.element84.com/v1/' --bbox='25,20,35,30' --collections='sentinel-2-l2a' --datetime='2023-01-01/2023-01-02'....used this command now. But now I am getting below mentioned error message....



Indexing from STAC API...
/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/pystac_client/item_search.py:850: FutureWarning: get_all_items() is deprecated, use item_collection() instead.
  warnings.warn(
11/03/2023 04:22:06: ERROR: Failed to handle item S2B_35QNE_20230101_0_L2A
Traceback (most recent call last):
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/odc/apps/dc_tools/stac_api_to_dc.py", line 194, in stac_api_to_odc
    _ = future.result()
        ^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/odc/apps/dc_tools/stac_api_to_dc.py", line 132, in process_item
    index_update_dataset(
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/odc/apps/dc_tools/utils.py", line 218, in index_update_dataset
    raise IndexingException(
odc.apps.dc_tools.utils.IndexingException: Failed to create dataset with error The dataset is not specifying all of the measurements in this product.
Missing fields are;
{'B04', 'B8A', 'B01', 'B11', 'B09', 'B07', 'SCL', 'B03', 'B05', 'B06', 'WVP', 'B02', 'AOT', 'B08', 'B12'}
 The URI was s3://sentinel-cogs/sentinel-s2-l2a-cogs/35/Q/NE/2023/1/S2B_35QNE_20230101_0_L2A/S2B_35QNE_20230101_0_L2A.json


Like this for many other similar messages. Any idea on this, as in what could go wrong.
Earlier to this I added a product with datacube product add s2_l2a.odc-product.yaml this command.

**Comment by chiranjivSharma** [comment]
Finally it shows- Added 0 Datasets, failed 87 Datasets, skipped 0 Datasets message

**Comment by alexgleith** [comment]
Ooh, the product definition needs to change too...

**Comment by chiranjivSharma** [comment]
you got any link to that other product definition yaml file and do I need to remove the earlier product definition file before adding the new one?

**Comment by alexgleith** [comment]
Can you please check this, maybe test the new product definition: https://github.com/opendatacube/datacube-dataset-config/compare/main...alexgleith-patch-1?quick_pull=1

You can update the product with `datacube product update --allow-unsafe <path-to-file>.yaml`

**Comment by chiranjivSharma** [comment]
Thanks it helped

**Comment by Cris70** [comment]
I had the same problem. I applied the fixes I found in this thread and it worked correctly, but it never finds any datasets.
I have tried several time intervals, but it always ends with `Added 0 Datasets, failed 0 Datasets, skipped 0 Datasets`.
Can you please suggest how to fix this problem, @alexgleith ?

**Comment by Cris70** [comment]
Had the same problem.
After fixing the API URL and the collection name, now I have a bunch of messages like this:
```
09/26/2025 12:47:44: WARNING: Couldn't find matching product for product name: sentinel_2_l2a
```
and finally:
```
Indexing from STAC API...
Added 0 Datasets, failed 0 Datasets, skipped 3039 Datasets
```
The file you referenced [here](https://github.com/opendatacube/odc-tools/issues/586#issuecomment-1791876634) is not available anymore.
Can you help with this problem @alexgleith ?

**Comment by alexgleith** [comment]
There's another flag to include to rename the product.

```bash
stac-to-dc --help
Usage: stac-to-dc [OPTIONS]

  Iterate through STAC items from a STAC API and add them to datacube.

Options:
  -E, --env TEXT                 The ODC environment to use.  Defaults to
                                 'default'.
  --limit INTEGER                Stop indexing after n datasets have been
                                 indexed.
  --update-if-exists             If the dataset or product already exists,
                                 update it instead of skipping it.
  --allow-unsafe                 Allow unsafe changes to a dataset. Take care!
  --catalog-href TEXT            URL to the catalog to search
  --collections TEXT             Comma separated list of collections to search
  --bbox TEXT                    Comma separated list of bounding box coords,
                                 lon-min, lat-min, lon-max, lat-max
  --datetime TEXT                Dates to search, either one day or an
                                 inclusive range, e.g. 2020-01-01 or
                                 2020-01-01/2020-01-02
  --options TEXT                 Other search terms, as a # separated list,
                                 i.e., --options=cloud_cover=0,100#sky=green
  --rename-product TEXT          Name of product to overwrite collection(s)
                                 names, only one product name can overwrite,
                                 despite multiple collections
  --url-string-replace TEXT      Replace a string in the STAC API URLs, e.g., '
                                 https://stac.example.com,s3://stac.example.or
                                 g'
  --archive-less-mature INTEGER  Archive existing any datasets that match
                                 product, time and region-code, but have lower
                                 dataset-maturity.Note: An error will be
                                 raised and the dataset add will fail if a
                                 matching dataset with higher or equal
                                 dataset-maturity.Can specify an of leniency
                                 for comparing timestamps, provided in
                                 milliseconds. Default value is 500ms.
  --publish-action TEXT          SNS topic arn to publish indexing/archiving
                                 actions to.
  --statsd-setting TEXT          statsd exporter hostname and port, i.e.
                                 prometheus-statsd-exporter:9125
  --help                         Show this message and exit.
```

So include `--rename-product=s2_l2a` and it should work.

**Comment by Cris70** [comment]
@alexgleith it worked perfectly, thank you
